version: '3.8'

services:
  postgres_keycloak:
    image: postgres:17
    container_name: postgres_keycloak
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432" 
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_SCHEMA: public
    ports:
      - "8090:8080"
    depends_on:
      - postgres_keycloak
    networks:
      - keycloak-net

volumes:
  keycloak_postgres_data:

networks:
  keycloak-net:
