name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag da imagem Docker'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Definir TAG manual
        id: vars
        run: echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_FRONT_IMAGE_NAME }}:${{ steps.vars.outputs.tag }} .

      - name: Enviar imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_FRONT_IMAGE_NAME }}:${{ steps.vars.outputs.tag }}