name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: Build From
        required: true
        default: 'main'
      image_tag:
        description: 'Tag da imagem Docker (ex: latest, v1.0.0)'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_FRONT_IMAGE_NAME }}:${{ github.event.inputs.image_tag }}

      - name: Enviar imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_FRONT_IMAGE_NAME }}:${{ github.event.inputs.image_tag }}