name: Generate Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'minor'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS }}
          config-file: release-please-config.json
          release-type: ${{ github.event.inputs.release_type }}